packages:
- BH
- CRM
- DBI
- DT
- FactoMineR
- KMsurv
- MASS
- MCMCvis
- MVN
- Matrix
- MatrixModels
- MuMIn
- QuickJSR
- R2admb
- R6
- RColorBrewer
- RMark
- Rcpp
- RcppArmadillo
- RcppEigen
- RcppParallel
- SparseM
- StanHeaders
- TMB
- abind
- askpass
- backports
- base64enc
- bit
- bit64
- blob
- bookdown
- boot
- brew
- brio
- broom
- bslib
- cachem
- callr
- car
- carData
- cellranger
- checkmate
- cli
- clipr
- cluster
- coda
- colorspace
- commonmark
- conflicted
- corrplot
- cowplot
- cpp11
- crayon
- credentials
- crosstalk
- curl
- data.table
- dbplyr
- dendextend
- desc
- devtools
- diffobj
- digest
- downlit
- dplyr
- dtplyr
- ellipse
- ellipsis
- emmeans
- energy
- estimability
- evaluate
- exactRankTests
- expm
- factoextra
- fansi
- farver
- fastmap
- fftwtools
- flashClust
- fontawesome
- forcats
- fs
- gargle
- generics
- gert
- ggplot2
- ggpubr
- ggrepel
- ggsci
- ggsignif
- ggtext
- gh
- gitcreds
- glue
- googledrive
- googlesheets4
- gridExtra
- gridtext
- gsl
- gtable
- haven
- highr
- hms
- htmltools
- htmlwidgets
- httpuv
- httr
- httr2
- ids
- ini
- inline
- insight
- isoband
- janitor
- jpeg
- jquerylib
- jsonlite
- kableExtra
- km.ci
- knitr
- labeling
- later
- lattice
- lazyeval
- leaps
- lifecycle
- lme4
- lmerTest
- loo
- lubridate
- magrittr
- markdown
- marked
- matrixStats
- matrixcalc
- maxstat
- mcmcse
- memoise
- mgcv
- mime
- miniUI
- minqa
- mnormt
- modelr
- moments
- mra
- msm
- multcompView
- munsell
- mvnormtest
- mvtnorm
- nlme
- nloptr
- nnet
- nortest
- numDeriv
- openssl
- optimx
- overlapping
- pbkrtest
- permute
- pillar
- pkgbuild
- pkgconfig
- pkgdown
- pkgload
- plyr
- png
- polynom
- postpack
- pracma
- praise
- prettyunits
- processx
- profvis
- progress
- promises
- ps
- psych
- purrr
- quantreg
- ragg
- rappdirs
- rcmdcheck
- readr
- readxl
- rematch
- rematch2
- remotes
- renv
- reprex
- reshape2
- rjags
- rlang
- rmarkdown
- roxygen2
- rprojroot
- rstan
- rstatix
- rstudioapi
- rversions
- rvest
- sass
- scales
- scatterplot3d
- selectr
- sessioninfo
- shiny
- snakecase
- sourcetools
- stringi
- stringr
- survMisc
- survival
- survminer
- svglite
- sys
- systemfonts
- telemetyr
- testthat
- textshaping
- tibble
- tidyr
- tidyselect
- tidyverse
- timechange
- tinytex
- truncnorm
- tzdb
- urlchecker
- usethis
- utf8
- uuid
- vctrs
- vegan
- viridis
- viridisLite
- vroom
- waldo
- webshot
- whisker
- withr
- xfun
- xml2
- xopen
- xtable
- yaml
- zip
- zoo
