---
title: "Survival analysis model"
output:
  html_document:
    df_print: paged
date: "2024-05-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = TRUE,
  comment = "#>"
)
```

```{r}
library(devtools)
library(postpack)
library(coda)
library(remotes)
library(rjags)
library(telemetyr)
library(dplyr)
library(ggplot2)
#library(anchors)
library(lubridate)
library(car)
library(lme4)
library(FactoMineR)
library(factoextra)
library(corrplot)
library(gridExtra)
library(mvnormtest)
library(MVN)
library(vegan)
library(permute)
library(lattice)
library(emmeans)
library(tidyr)
library(cluster)
library(ggrepel)
library(lmerTest)
library(survival)
library(survminer)
library(MuMIn)
library(CRM)
library(TMB)
library(RMark)
library(marked)
library(mra)
library(tidyverse)
#library(mark)
library(knitr)
library(MCMCvis)

```

```{r}
getwd()
survdata <- read_csv("~/Library/Mobile\ Documents/com~apple~CloudDocs/Documents/Personal/jel000-notes/Capstone/Bottlenecks_MDS_Capstone/survival_analysis/data/preprocessed/preprocessed.csv")
# survdata <- read.delim("~/Library/Mobile\ Documents/com~apple~CloudDocs/Documents/Personal/jel000-notes/Capstone/Bottlenecks_MDS_Capstone/documentation/sample_code/data6.txt", sep = " ")

survdata

# Removing the first col (index, not needed)
survdata <- survdata[,2:8]
head(survdata)
```

```{r}
nrow(survdata[which(survdata$origin == "wild"),])
nrow(survdata[which(survdata$origin == "hatch"),])
```

```{r}
# nrow(survdata[which(survdata$species == "stl"),])
# # Issue: There are too less stl data. 
nrow(survdata[which(survdata$species == "ck"),])
nrow(survdata[which(survdata$species == "co"),])
```

```{r}
survdata <- survdata[survdata$species %in% c("co", "ck"), ]
survdata <- survdata[sample(nrow(survdata), 1000, replace = FALSE), ]
nrow(survdata)
```

```{r}
survdata$stage<-as.factor(survdata$stage)
survdata$origin<-as.factor(survdata$origin)
survdata$action<-as.factor(survdata$action)
survdata$juliandate <- yday(survdata$date)  
survdata$juliandate<-as.factor(survdata$juliandate)
survdata$species<-as.factor(survdata$species)
```

```{r}
## Create two separate datasets for wild vs hatchery fish

hatchsurv <- survdata

# wildsurv <- survdata[which(substr(survdata$origin,1,4)=="wild"),] 
# hatchsurv <- survdata[which(substr(survdata$origin,1,5)=="hatch"),] 
```

```{r}
hatchsurv$action <- droplevels(hatchsurv$action)
```

```{r}
# Finding fishes that were tagged at hatchery, and tracking their path
hatchtag <- hatchsurv[which(substr(hatchsurv$action,1,3)=="tag"),]

hatchdown <- hatchsurv[which(substr(hatchsurv$stage,1,10)=="downstream"),] 

hatchestuary <- hatchsurv[ which( hatchsurv$stage == "estuary" & 
                                    hatchsurv$action == "detect") , ]

hatchmicro <- hatchsurv[which(substr(hatchsurv$stage,1,5)=="micro" &
                                hatchsurv$action == "detect" ),]

hatchreturn <- hatchsurv[which(substr(hatchsurv$stage,1,6)=="return"),]
```

```{r}
library(purrr)
library(dplyr)
df_list <- list(hatchtag, hatchdown, hatchestuary, hatchmicro, hatchreturn)
```

```{r}
# Create a table such that there is only one row for each tag_id
hatchtotal <- df_list |> reduce(full_join, by='tag_id')
```

```{r}

# Columns t1, t2, t3 etc created to see if that fish was seen in those specific stages

hatchtotal$t1 <- with(hatchtotal, ifelse(stage.x %in% c("facility") & 
                                           action.x == "tag", 
                                         "1", "0"))

hatchtotal$t2 <- with(hatchtotal, ifelse(stage.y %in% c("downstream") & 
                                           action.y == "detect", 
                                         "1", "0"))

hatchtotal$t3 <- with(hatchtotal, ifelse(stage.x %in% c("estuary") |
                                           stage.x.x %in% c("estuary"),
                                         "1", "0"))

hatchtotal$t4 <- with(hatchtotal, ifelse(stage.x %in% c("micro") |
                                           stage.y.y %in% c("micro"),
                                         "1", "0"))

hatchtotal$t5 <- with(hatchtotal, ifelse(stage %in% c("return"),
                                         "1", "0"))
```

```{r}
hatchtotal$origin.x <- with(hatchtotal, ifelse(origin.x == "hatch",
                                         "1", "0"))
hatchtotal
```

```{r}
hatchtotal$t1 <- as.factor(hatchtotal$t1)
hatchtotal$t2 <- as.factor(hatchtotal$t2)
hatchtotal$t3 <- as.factor(hatchtotal$t3)
hatchtotal$t4 <- as.factor(hatchtotal$t4)
hatchtotal$t5 <- as.factor(hatchtotal$t5)

# --- ADDED BY JENNY
hatchtotal$origin.x <- as.factor(hatchtotal$origin.x)
```

```{r}

# Eg: The values in t1, t2 etc are 0,0,1,1,1, then ch is 00111
hatchtotal$ch <- paste(hatchtotal$t1, hatchtotal$t2, hatchtotal$t3, hatchtotal$t4, hatchtotal$t5, sep = "")
```

```{r}
head(hatchtotal)
```

```{r}
#rename some columns
names(hatchtotal)[names(hatchtotal) == "ch"] <- "cap_hist"
hatchtotal$duty_cycle <- "batch_1"
head(hatchtotal)
```

```{r}
hatchtotal$tag_id<-as.numeric(as.character(hatchtotal$tag_id))
hatchtotal$t1<-as.numeric(as.character(hatchtotal$t1))
hatchtotal$t2<-as.numeric(as.character(hatchtotal$t2))
hatchtotal$t3<-as.numeric(as.character(hatchtotal$t3))
hatchtotal$t4<-as.numeric(as.character(hatchtotal$t4))
hatchtotal$t5<-as.numeric(as.character(hatchtotal$t5))

hatchtotal$cap_hist<-as.numeric(as.character(hatchtotal$cap_hist))
# hatchtotal$origin.x<-as.numeric(hatchtotal$origin.x)
```

```{r}
head(hatchtotal)
```

```{r}
#Make a simpler dataset with just the columns we want
#hatchsimple <- hatchtotal[c(1, 37, 32:36)]
hatchsimple <- hatchtotal[c(1, 42, 4, 37:41)]
names(hatchsimple)[names(hatchsimple) == "origin.x"] <- "origin"
head(hatchsimple)
head(hatchtotal)

hatchsimple2 <- hatchsimple[!duplicated(hatchsimple$tag_id), ]
hatchsimple2
```

```{r}
sum(is.na(hatchsimple2$origin))
nrow(hatchsimple2[which(hatchsimple2$origin == 1),])
nrow(hatchsimple2[which(hatchsimple2$origin == 0),])
```

```{r}
hatchsimple_clean <- hatchsimple2[!is.na(hatchsimple2$origin), ]
hatchsimple_clean <- hatchsimple_clean |>
  mutate(origin = as.numeric(origin),
         origin = origin - 1)
hatchsimple_clean
nrow(hatchsimple_clean)
```

```{r}

write_bayes_cjs = function(file_path = NULL) {
  
  if(is.null(file_path)) file_path = 'CJS_model.txt'
  
  # specify model in JAGS
  jags_model = function() {
    
    # PRIORS AND CONSTRAINTS
    phi[1] <- 1
    p[1] <- 1
    
    for(j in 2:J) {
      phi[j] ~ dbeta(1,1) # survival probability between arrays
    }
    
    for(j in 2:(J-1)) {
      p[j] ~ dbeta(1,1) # detection probability between arrays
    }
    
    p[J] <- 0.95  # this constrains the model and allows user to input the known detection efficiency of final PIT receiver
    
    # LIKELIHOOD 
    for (i in 1:N) {
      # j = f[i] is the release occasion - known alive; i.e., the tagging event
      for (j in (f[i] + 1):J) {
        
        # survival process: 
        z[i,j] ~ dbern(phi[j] * z[i,j-1]) # fish i in period j is a bernoulli trial
        
        # detection process: 
        y[i,j] ~ dbern(p[j] * z[i,j]) # another bernoulli trial
      }
    }
    
    survship[1] <- 1 # the tagging stage (stage 1)
    for (j in 2:J) { # the rest of the stages (stages 2-5)
      survship[j] <- survship[j-1] * phi[j]
    }
  }
  
  postpack::write_model(jags_model, file_path)
}

write_bayes_cjs(file_path = 'CJS_model_edited.txt')
```

```{r}
model_content <- readLines("CJS_model_edited.txt")  # Replace "path_to_your_model_file.txt" with the actual path to your file
# Print line 19
print(model_content[14])
```

```{r}
jags_data = prep_jags_cjs(
  cap_hist_wide = hatchsimple_clean,
  tag_meta = hatchtotal,
  drop_col_nm = "duty_cycle",
  drop_values = c("batch_2", "batch_3")
)

```

```{r}
cjs_post = run_jags_cjs(file_path = 'CJS_model_edited.txt',
                        jags_data = jags_data,
                        n_chains = 4,
                        n_adapt = 1000,
                        n_burnin = 2500,
                        n_iter = 2500,
                        n_thin = 5,
                        params_to_save = c("phi", "p", "survship", "b0", "b1"),
                        rng_seed = 4)
```

```{r}
# Summarise the posterior samples 

param_summ = summarise_jags_cjs(cjs_post)
param_summ
```

```{r}
logit_subset = param_summ[which(param_summ$param_grp == "logit"),]
logit_subset
```

```{r}
param_summ = param_summ %<>%
  left_join(tibble(site = colnames(jags_data$y)) %>%
              mutate(site = factor(site, levels = site),
                     site_num = as.integer(site))) %>%
  select(param_grp, site_num,
         site,
         param,
         everything())
```

```{r}
surv_p = param_summ %>%
  filter(param_grp == 'survship') %>%
  ggplot(aes(x = site,
             y = mean)) +
  geom_errorbar(aes(ymin = `2.5%`,
                    ymax = `97.5%`),
                width = 0) +
  scale_x_discrete(breaks=c("t1","t2","t3", "t4", "t5"),
                   labels=c("Hatchery", "Downstream", "Estuary", "Microtroll", "Adult return")) +
  geom_point() +
  theme_classic() +
  labs(x = '',
       y = 'Cumulative Survival')+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

surv_p
ggsave("~/Library/Mobile\ Documents/com~apple~CloudDocs/Documents/Personal/jel000-notes/Capstone/Bottlenecks_MDS_Capstone/survival_analysis/plots/surv_p.png", plot = surv_p, width = 8, height = 6, dpi = 300)
```

```{r}
phi_p = param_summ %>%
  filter(param_grp == 'phi') %>%
  ggplot(aes(x = site,
             y = mean)) +
  geom_errorbar(aes(ymin = `2.5%`,
                    ymax = `97.5%`),
                width = 0) +
  scale_x_discrete(breaks=c("t1","t2","t3", "t4", "t5"),
                   labels=c("Hatchery", "Downstream", "Estuary", "Microtroll", "Adult return")) +
  geom_point() +
  theme_classic() +
  labs(x = '',
       y = 'Survival From Previous Site')+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

phi_p
```

```{r}
det_p = param_summ %>%
  filter(param_grp == 'p') %>%
  ggplot(aes(x = site,
             y = mean)) +
  geom_errorbar(aes(ymin = `2.5%`,
                    ymax = `97.5%`),
                width = 0) +
  scale_x_discrete(breaks=c("t1","t2","t3", "t4", "t5"),
                     labels=c("Hatchery", "Downstream", "Estuary", "Microtroll", "Adult return")) +
  geom_point() +
  theme_classic() +
  labs(x = '',
       y = 'Detection Probability')+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

det_p
```

```{r}
ggarrange(det_p, phi_p, surv_p,
          labels = c("A", "B", "C"),
          ncol = 3, nrow = 1)
postpack::diag_plots(cjs_post, "phi",
                     layout = "4x2")
postpack::diag_plots(cjs_post, "survship",
                     layout = "4x2")
postpack::diag_plots(cjs_post, "^p[",
                     layout = "4x2")
```

```{r}
curve(dbeta(x, shape1 = 9, shape2 = 1), from = 0, to = 1, 
      main = "Beta Distribution", xlab = "x", ylab = "Density")
```

```{r}
PR <- rbeta(5000, 1,1)
MCMCtrace(cjs_post, params = 'phi', priors = PR, Rhat = T, n.eff = T,  ind = TRUE, pdf = FALSE)
```

```{r}
PR <- rbeta(5000, 7,3)
MCMCtrace(cjs_post, params = 'phi', priors = PR, Rhat = T, n.eff = T,  ind = TRUE, pdf = FALSE)


```

```{r}
PR <- rbeta(5000, 9,1)
MCMCtrace(cjs_post, params = 'phi', priors = PR, Rhat = T, n.eff = T,  ind = TRUE, pdf = FALSE)
```

```{r}
PR <- rbeta(5000, 6,4)
MCMCtrace(cjs_post, params = 'phi', priors = PR, Rhat = T, n.eff = T,  ind = TRUE, pdf = FALSE)
```

```{r}
PR <- rbeta(5000, 1,9)
MCMCtrace(cjs_post, params = 'phi', priors = PR, Rhat = T, n.eff = T,  ind = TRUE, pdf = FALSE)
```

```{r}
MCMCtrace(cjs_post, params = 'p', priors = PR, Rhat = T, n.eff = T, 
          exact = TRUE, ind = TRUE, pdf = FALSE)
MCMCtrace(cjs_post, params = 'phi', priors = PR, Rhat = T, n.eff = T, 
          exact = TRUE, ind = TRUE, pdf = FALSE)
MCMCtrace(cjs_post, params = 'survship', priors = PR, Rhat = T, n.eff = T, 
          exact = TRUE, ind = TRUE, pdf = FALSE)
```

```{r}
densityplot(hatchtotal$t2)
```

```{r}
postpack::get_params(cjs_post)
postpack::post_dim(cjs_post)
postpack::post_summ(cjs_post, "phi")
postpack::post_summ(cjs_post, "p")
postpack::post_summ(cjs_post, "survship")

# postpack::post_summ(cjs_post)
```

```{r}
data(cjs_post)
head(cjs_post)
PR <- rbeta(2000, 10,100)
curve(dbeta(x, shape1 = 10, shape2 = 90), from = 0, to = 1, 
      main = "Beta Distribution", xlab = "x", ylab = "Density")
MCMCtrace(cjs_post, params = 'phi', priors = PR, exact = TRUE, ind = TRUE, pdf = FALSE)
```

```{r}
# Creating the Sequence
gfg = seq(0, 1, by = 0.1)

# Plotting the beta density
plot(gfg, dbeta(gfg, 2,3), xlab="X",
     ylab = "Beta Density", type = "l",
     col = "Red")


head(MCMC_data)
head(cjs_post)
```

```{r}
set.seed(182)
nsims <- 1000
PR <- rbeta(nsims, 1,1)

simd <- tibble(prop = (hatchtotal$t1-mean(hatchtotal$t1))/sd(hatchtotal$t1))


## Prior predictive checks
set.seed(182)
nsims <- 100
sigma <- 1 / sqrt(rgamma(nsims, 1, rate = 100))
beta0 <- rnorm(nsims, 1,1)
beta1 <- rnorm(nsims, 1,1)

for(i in 1:nsims){
  this_mu <- beta0[i] + beta1[i]*simd$prop 
  simd[paste0(i)] <- this_mu + rnorm(nrow(simd), 0, sigma[i])
}


# dsims <- tibble(log_gest_c = (log(ds$gest)-mean(log(ds$gest)))/sd(log(ds$gest)))
# 
# for(i in 1:nsims){
#   this_mu <- beta0[i] + beta1[i]*dsims$log_gest_c 
#   dsims[paste0(i)] <- this_mu + rnorm(nrow(dsims), 0, sigma[i])
# }
# 
# dsl <- simd %>% 
#   pivot_longer(`1`:`10`, names_to = "sim", values_to = "sim_weight")
# 
# dsl %>% 
#   ggplot(aes(sim_weight)) + geom_histogram(aes(y = ..density..), bins = 20, fill = "turquoise", color = "black") + 
#   xlim(c(-1000, 1000)) + 
#   geom_vline(xintercept = log(60), color = "purple", lwd = 1.2, lty = 2) + 
#   theme_bw(base_size = 16) + 
#   annotate("text", x=300, y=0.0022, label= "Monica's\ncurrent weight", 
#            color = "purple", size = 5) 

```

```{r}
# Sample 10000 draws from Beta(45,55) prior
# prior_A <- rbeta(n = 50000, shape1 = 60, shape2 = 40)
# 
# # Store the results in a data frame
# prior_sim <- data.frame(prior_A)
# 
# # Construct a density plot of the prior sample
# ggplot(prior_sim, aes(x = prior_A)) + 
  # geom_density()
```
